### ISSUE TITLE
error in installation

### ISSUE THREAD

**Issue by adw96** [statdivlab/q2-breakaway#13]
```
> library("devtools"); options(unzip = "internal"); devtools::install_url("https://github.com/adw96/breakaway/archive/master.zip")
Downloading package from url: https://github.com/adw96/breakaway/archive/master.zip
Installing breakaway
trying URL 'https://cran.rstudio.com/src/contrib/dplyr_0.7.6.tar.gz'
Content type 'application/x-gzip' length 710339 bytes (693 KB)
==================================================
downloaded 693 KB

sh: /bin/tar: No such file or directory
sh: /bin/tar: No such file or directory
Installation failed: error in running command
trying URL 'https://cran.rstudio.com/src/contrib/ggplot2_3.0.0.tar.gz'
Content type 'application/x-gzip' length 2847050 bytes (2.7 MB)
==================================================
downloaded 2.7 MB

sh: /bin/tar: No such file or directory
sh: /bin/tar: No such file or directory
Installation failed: error in running command
trying URL 'https://cran.rstudio.com/src/contrib/MASS_7.3-50.tar.gz'
Content type 'application/x-gzip' length 487690 bytes (476 KB)
==================================================
downloaded 476 KB

sh: /bin/tar: No such file or directory
sh: /bin/tar: No such file or directory
Installation failed: error in running command
trying URL 'https://cran.rstudio.com/src/contrib/R.rsp_0.42.0.tar.gz'
Content type 'application/x-gzip' length 842386 bytes (822 KB)
==================================================
downloaded 822 KB

sh: /bin/tar: No such file or directory
sh: /bin/tar: No such file or directory
Installation failed: error in running command
'/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/j_/4kw5ygpn39d937k0tbcbr_lw0000gp/T/Rtmps7rMcS/devtoolscced2c35f023/breakaway-master'  \
  --library='/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/library'  \
  --install-tests 

* installing *source* package ‘breakaway’ ...
** R
** data
*** moving datasets to lazyload DB
** tests
** preparing package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (breakaway)
Warning messages:
1: In utils::untar(src, exdir = target, compressed = "gzip") :
  ‘/bin/tar -xf '/var/folders/j_/4kw5ygpn39d937k0tbcbr_lw0000gp/T//Rtmps7rMcS/dplyr_0.7.6.tar.gz' -C '/var/folders/j_/4kw5ygpn39d937k0tbcbr_lw0000gp/T//Rtmps7rMcS/devtoolscced928a082'’ returned error code 127
2: In utils::untar(src, exdir = target, compressed = "gzip") :
  ‘/bin/tar -xf '/var/folders/j_/4kw5ygpn39d937k0tbcbr_lw0000gp/T//Rtmps7rMcS/ggplot2_3.0.0.tar.gz' -C '/var/folders/j_/4kw5ygpn39d937k0tbcbr_lw0000gp/T//Rtmps7rMcS/devtoolscced13210307'’ returned error code 127
3: In utils::untar(src, exdir = target, compressed = "gzip") :
  ‘/bin/tar -xf '/var/folders/j_/4kw5ygpn39d937k0tbcbr_lw0000gp/T//Rtmps7rMcS/MASS_7.3-50.tar.gz' -C '/var/folders/j_/4kw5ygpn39d937k0tbcbr_lw0000gp/T//Rtmps7rMcS/devtoolscced3d797a3b'’ returned error code 127
4: In utils::untar(src, exdir = target, compressed = "gzip") :
  ‘/bin/tar -xf '/var/folders/j_/4kw5ygpn39d937k0tbcbr_lw0000gp/T//Rtmps7rMcS/R.rsp_0.42.0.tar.gz' -C '/var/folders/j_/4kw5ygpn39d937k0tbcbr_lw0000gp/T//Rtmps7rMcS/devtoolscced68b8925f'’ returned error code 127
> 
> 
```

**Comment by adw96** [comment]
`(qiime2-2018.6) D-10-18-245-180:~ adwillis$ R -e 'devtools::install_github("adw96/breakaway")'

R version 3.4.1 (2017-06-30) -- "Single Candle"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin14.5.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Previously saved workspace restored]

> devtools::install_github("adw96/breakaway")
Downloading GitHub repo adw96/breakaway@master
from URL https://api.github.com/repos/adw96/breakaway/zipball/master
Installing breakaway
trying URL 'https://cran.rstudio.com/src/contrib/dplyr_0.7.6.tar.gz'
Content type 'application/x-gzip' length 710339 bytes (693 KB)
==================================================
downloaded 693 KB

Installing dplyr
trying URL 'https://cran.rstudio.com/src/contrib/bindrcpp_0.2.2.tar.gz'
Content type 'application/x-gzip' length 10212 bytes
==================================================
downloaded 10212 bytes

Installing bindrcpp
trying URL 'https://cran.rstudio.com/src/contrib/Rcpp_0.12.18.tar.gz'
Content type 'application/x-gzip' length 3809164 bytes (3.6 MB)
==================================================
downloaded 3.6 MB

Installing Rcpp
'/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/j_/4kw5ygpn39d937k0tbcbr_lw0000gp/T/RtmpH1nMYc/devtoolsfeb83675985b/Rcpp'  \
  --library='/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/library'  \
  --install-tests 

* installing *source* package ‘Rcpp’ ...
** package ‘Rcpp’ successfully unpacked and MD5 sums checked
** libs
clang++  -I/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/include -DNDEBUG -I../inst/include/  -I/Users/adwillis/anaconda3/envs/qiime2-2018.6/include   -fPIC  -I/Users/adwillis/anaconda3/envs/qiime2-2018.6/include  -c Date.cpp -o Date.o
In file included from Date.cpp:31:
In file included from ../inst/include/Rcpp.h:27:
In file included from ../inst/include/RcppCommon.h:29:
In file included from ../inst/include/Rcpp/r/headers.h:48:
In file included from ../inst/include/Rcpp/platform/compiler.h:100:
In file included from /Users/adwillis/anaconda3/envs/qiime2-2018.6/include/c++/v1/cmath:305:
/Users/adwillis/anaconda3/envs/qiime2-2018.6/include/c++/v1/math.h:301:15: fatal error: 'math.h' file not found
#include_next <math.h>
              ^~~~~~~~
1 error generated.
make: *** [Date.o] Error 1
ERROR: compilation failed for package ‘Rcpp’
* removing ‘/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/library/Rcpp’
* restoring previous ‘/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/library/Rcpp’
Installation failed: Command failed (1)
'/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/j_/4kw5ygpn39d937k0tbcbr_lw0000gp/T/RtmpH1nMYc/devtoolsfeb86ec6ed67/bindrcpp'  \
  --library='/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/library'  \
  --install-tests 

* installing *source* package ‘bindrcpp’ ...
** package ‘bindrcpp’ successfully unpacked and MD5 sums checked
** libs
clang++  -I/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/include -DNDEBUG -I../inst/include -I. -I"/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/library/plogr/include" -I"/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/library/Rcpp/include" -I/Users/adwillis/anaconda3/envs/qiime2-2018.6/include   -fPIC  -I/Users/adwillis/anaconda3/envs/qiime2-2018.6/include  -c RcppExports.cpp -o RcppExports.o
In file included from RcppExports.cpp:4:
In file included from ./../inst/include/bindrcpp.h:7:
In file included from ../inst/include/bindrcpp_RcppExports.h:7:
In file included from ../inst/include/bindrcpp_types.h:4:
In file included from /Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/library/Rcpp/include/RcppCommon.h:38:
In file included from /Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/library/Rcpp/include/Rcpp/r/headers.h:48:
In file included from /Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/library/Rcpp/include/Rcpp/platform/compiler.h:103:
In file included from /Users/adwillis/anaconda3/envs/qiime2-2018.6/include/c++/v1/cmath:305:
/Users/adwillis/anaconda3/envs/qiime2-2018.6/include/c++/v1/math.h:301:15: fatal error: 'math.h' file not found
#include_next <math.h>
              ^~~~~~~~
1 error generated.
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘bindrcpp’
* removing ‘/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/library/bindrcpp’
* restoring previous ‘/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/library/bindrcpp’
Installation failed: Command failed (1)
trying URL 'https://cran.rstudio.com/src/contrib/glue_1.3.0.tar.gz'
Content type 'application/x-gzip' length 56368 bytes (55 KB)
==================================================
downloaded 55 KB

Installing glue
'/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/j_/4kw5ygpn39d937k0tbcbr_lw0000gp/T/RtmpH1nMYc/devtoolsfeb85e3ea111/glue'  \
  --library='/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/library'  \
  --install-tests 

* installing *source* package ‘glue’ ...
** package ‘glue’ successfully unpacked and MD5 sums checked
** libs
clang -I/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/include -DNDEBUG   -I/Users/adwillis/anaconda3/envs/qiime2-2018.6/include   -fPIC  -I/Users/adwillis/anaconda3/envs/qiime2-2018.6/include  -c glue.c -o glue.o
In file included from glue.c:1:
/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/include/Rinternals.h:39:11: fatal error: 'stdio.h' file not
      found
# include <stdio.h>
          ^~~~~~~~~
1 error generated.
make: *** [glue.o] Error 1
ERROR: compilation failed for package ‘glue’
* removing ‘/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/library/glue’
* restoring previous ‘/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/library/glue’
Installation failed: Command failed (1)
trying URL 'https://cran.rstudio.com/src/contrib/Rcpp_0.12.18.tar.gz'
Content type 'application/x-gzip' length 3809164 bytes (3.6 MB)
==================================================
downloaded 3.6 MB

Skipping Rcpp, it is already being installed.
trying URL 'https://cran.rstudio.com/src/contrib/rlang_0.2.2.tar.gz'
Content type 'application/x-gzip' length 325128 bytes (317 KB)
==================================================
downloaded 317 KB

Installing rlang
'/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/j_/4kw5ygpn39d937k0tbcbr_lw0000gp/T/RtmpH1nMYc/devtoolsfeb82d1f0e89/rlang'  \
  --library='/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/library'  \
  --install-tests 

* installing *source* package ‘rlang’ ...
** package ‘rlang’ successfully unpacked and MD5 sums checked
** libs
clang -I/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/include -DNDEBUG -I./lib/  -I/Users/adwillis/anaconda3/envs/qiime2-2018.6/include   -fPIC  -I/Users/adwillis/anaconda3/envs/qiime2-2018.6/include  -c capture.c -o capture.o
In file included from capture.c:1:
/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/include/Rinternals.h:39:11: fatal error: 'stdio.h' file not
      found
# include <stdio.h>
          ^~~~~~~~~
1 error generated.
make: *** [capture.o] Error 1
ERROR: compilation failed for package ‘rlang’
* removing ‘/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/library/rlang’
* restoring previous ‘/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/library/rlang’
Installation failed: Command failed (1)
trying URL 'https://cran.rstudio.com/src/contrib/tidyselect_0.2.4.tar.gz'
Content type 'application/x-gzip' length 21702 bytes (21 KB)
==================================================
downloaded 21 KB

Installing tidyselect
trying URL 'https://cran.rstudio.com/src/contrib/glue_1.3.0.tar.gz'
Content type 'application/x-gzip' length 56368 bytes (55 KB)
==================================================
downloaded 55 KB

Skipping glue, it is already being installed.
trying URL 'https://cran.rstudio.com/src/contrib/purrr_0.2.5.tar.gz'
Content type 'application/x-gzip' length 126147 bytes (123 KB)
==================================================
downloaded 123 KB

Installing purrr
trying URL 'https://cran.rstudio.com/src/contrib/rlang_0.2.2.tar.gz'
Content type 'application/x-gzip' length 325128 bytes (317 KB)
==================================================
downloaded 317 KB

Skipping rlang, it is already being installed.
'/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/j_/4kw5ygpn39d937k0tbcbr_lw0000gp/T/RtmpH1nMYc/devtoolsfeb8737d8c3d/purrr'  \
  --library='/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/library'  \
  --install-tests 

* installing *source* package ‘purrr’ ...
** package ‘purrr’ successfully unpacked and MD5 sums checked
** libs
clang -I/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/include -DNDEBUG   -I/Users/adwillis/anaconda3/envs/qiime2-2018.6/include   -fPIC  -I/Users/adwillis/anaconda3/envs/qiime2-2018.6/include  -c backports.c -o backports.o
In file included from backports.c:2:
/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/include/R.h:55:11: fatal error: 'stdlib.h' file not found
# include <stdlib.h> /* Not used by R itself, but widely assumed in packages */
          ^~~~~~~~~~
1 error generated.
make: *** [backports.o] Error 1
ERROR: compilation failed for package ‘purrr’
* removing ‘/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/library/purrr’
* restoring previous ‘/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/library/purrr’
Installation failed: Command failed (1)
trying URL 'https://cran.rstudio.com/src/contrib/Rcpp_0.12.18.tar.gz'
Content type 'application/x-gzip' length 3809164 bytes (3.6 MB)
==================================================
downloaded 3.6 MB

Skipping Rcpp, it is already being installed.
trying URL 'https://cran.rstudio.com/src/contrib/rlang_0.2.2.tar.gz'
Content type 'application/x-gzip' length 325128 bytes (317 KB)
==================================================
downloaded 317 KB

Skipping rlang, it is already being installed.
'/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/j_/4kw5ygpn39d937k0tbcbr_lw0000gp/T/RtmpH1nMYc/devtoolsfeb831e685d/tidyselect'  \
  --library='/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/library'  \
  --install-tests 

* installing *source* package ‘tidyselect’ ...
** package ‘tidyselect’ successfully unpacked and MD5 sums checked
** libs
clang++  -I/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/include -DNDEBUG  -I"/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/library/Rcpp/include" -I/Users/adwillis/anaconda3/envs/qiime2-2018.6/include   -fPIC  -I/Users/adwillis/anaconda3/envs/qiime2-2018.6/include  -c RcppExports.cpp -o RcppExports.o
In file included from RcppExports.cpp:4:
In file included from /Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/library/Rcpp/include/Rcpp.h:27:
In file included from /Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/library/Rcpp/include/RcppCommon.h:38:
In file included from /Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/library/Rcpp/include/Rcpp/r/headers.h:48:
In file included from /Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/library/Rcpp/include/Rcpp/platform/compiler.h:103:
In file included from /Users/adwillis/anaconda3/envs/qiime2-2018.6/include/c++/v1/cmath:305:
/Users/adwillis/anaconda3/envs/qiime2-2018.6/include/c++/v1/math.h:301:15: fatal error: 'math.h' file not found
#include_next <math.h>
              ^~~~~~~~
1 error generated.
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘tidyselect’
* removing ‘/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/library/tidyselect’
Installation failed: Command failed (1)
'/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/j_/4kw5ygpn39d937k0tbcbr_lw0000gp/T/RtmpH1nMYc/devtoolsfeb85ecdd3c3/dplyr'  \
  --library='/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/library'  \
  --install-tests 

ERROR: dependency ‘tidyselect’ is not available for package ‘dplyr’
* removing ‘/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/library/dplyr’
Installation failed: Command failed (1)
trying URL 'https://cran.rstudio.com/src/contrib/MASS_7.3-50.tar.gz'
Content type 'application/x-gzip' length 487690 bytes (476 KB)
==================================================
downloaded 476 KB

Installing MASS
'/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/j_/4kw5ygpn39d937k0tbcbr_lw0000gp/T/RtmpH1nMYc/devtoolsfeb82916b0a0/MASS'  \
  --library='/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/library'  \
  --install-tests 

* installing *source* package ‘MASS’ ...
** package ‘MASS’ successfully unpacked and MD5 sums checked
** libs
clang -I/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/include -DNDEBUG   -I/Users/adwillis/anaconda3/envs/qiime2-2018.6/include   -fPIC  -I/Users/adwillis/anaconda3/envs/qiime2-2018.6/include  -c MASS.c -o MASS.o
MASS.c:18:10: fatal error: 'stdlib.h' file not found
#include <stdlib.h>
         ^~~~~~~~~~
1 error generated.
make: *** [MASS.o] Error 1
ERROR: compilation failed for package ‘MASS’
* removing ‘/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/library/MASS’
* restoring previous ‘/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/library/MASS’
Installation failed: Command failed (1)
'/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/j_/4kw5ygpn39d937k0tbcbr_lw0000gp/T/RtmpH1nMYc/devtoolsfeb85e4a4841/adw96-breakaway-16396eb'  \
  --library='/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/library'  \
  --install-tests 

ERROR: dependency ‘dplyr’ is not available for package ‘breakaway’
* removing ‘/Users/adwillis/anaconda3/envs/qiime2-2018.6/lib/R/library/breakaway’
Installation failed: Command failed (1)`

**Comment by paulinetrinh** [comment]
moved installation of `breakaway` into R script.
