### ISSUE TITLE
Plugin error when running breakaway in qiime2

### ISSUE THREAD

**Issue by insectnate** [statdivlab/q2-breakaway#29]
I am trying to use breakaway to model estimated alpha diversity per suggestions from the qiime2 forum.  Breakaway installs without error via conda and pip. However when I run the command 
qiime breakaway alpha \
--i-table table-dada2.qza \
--o-alpha-diversity alpha_div/richness-better.qza
I get the following error message 

Plugin error from breakaway:

  Command '['run_new_richness.R', '/tmp/tmpbpkmn_rc/table.tsv', '/tmp/q2-AlphaDiversityFormat-iplggw0r']' returned non-zero exit status 1

looking at the log file it was looking for gtar and gzip
gzip was in /bin/gzip and not /usr/bin/gzip
I added gzip to /usr/bin but I still get the error...

Attached is the error log file.
[breakaway_error_2.log](https://github.com/statdivlab/q2-breakaway/files/2809620/breakaway_error_2.log)

**Comment by adw96** [comment]
@paulinetrinh Can you help with this one? Thanks!

**Comment by paulinetrinh** [comment]
@insectnate Thanks for pointing this out! This seems to be a problem with the path not being appropriately recognized. 

You should be able to fix this error if in your qiime2 conda environment you run the following: 

`R -e 'Sys.setenv(TAR = "/bin/tar"); library(devtools); devtools::install_github("adw96/breakaway")' `

and then try running the qiime breakaway command after that finishes compiling. 

Let me know if that works!

**Comment by insectnate** [comment]
It did! Thanks so much Pauline! One note I had to change my sampleIDs in my metadata file to have an X at the beginning to match how R changes them during import since mine are just numeric strings.
Awesome tool! Thanks again!

Nathan
