### ISSUE TITLE
Sample names are modified in the alpha diversity output

### ISSUE THREAD

**Issue by fedarko** [statdivlab/q2-breakaway#32]
Hi, and thanks for developing q2-breakaway!

The sample IDs in a dataset I'm looking at right now all start with numbers, so it looks like q2-breakaway is prefixing all of the IDs with an `X`. (From searching, it looks like this issue was briefly mentioned before [here](https://github.com/statdivlab/q2-breakaway/issues/29#issuecomment-459025509).) I _think_ this is happening due to the call to  `read.table()` [here](https://github.com/statdivlab/q2-breakaway/blob/9bd1f4f5fd88499c180aa8d0d6d85ae538ae55b2/q2_breakaway/assets/run_new_richness.R#L44).

This doesn't cause any problems within q2-breakaway per se, but it's complicating the process of using the Breakaway output in other contexts in QIIME 2 (I'm currently trying to make a longitudinal plot that includes Breakaway's output, and since none of the sample IDs match up I need to export the alpha diversity, remove the starting `X`s, and then re-import the alpha diversity). I imagine other people using this plugin will probably encounter these same problems eventually?

For whatever it's worth I remember running into this same issue in q2-aldex2, another plugin that communicates between QIIME 2 and R -- [the solution](https://github.com/ggloor/q2-aldex2/commit/7a8456ed9023d1aa2bfa60447fb31fd68509d59d) @dgiguer had for that was using `check.names=FALSE`, although that was with `read.delim()` instead of `read.table()`. It looks like this option is also available for `read.table()`, but I don't know enough R to say for sure if that's a reasonable thing to do in this case...

In any case, thank you again for your work on this package! Looking forward to using it more :)

**Comment by dgiguer** [comment]
`check.names=FALSE` is always a pain. @fedarko is right, it should work in this case for `read.table()`

**Comment by paulinetrinh** [comment]
@fedarko are your samples ID names numeric?

**Comment by fedarko** [comment]
@paulinetrinh In the dataset I'm working with, some sample IDs only include numeric/period characters (e.g. `10283.000065607`),  and some include non-numeric characters but still start with a number (e.g. `10283.LS.1.14.2015`). In either case, the sample IDs in the `alpha-diversity.tsv` file start with `X`.

As I understand it, Qiita prefixes all sample IDs in a study with the study number... so this is probably going to be a common situation, unfortunately.

**Comment by paulinetrinh** [comment]
Thanks @fedarko! The problem should be fixed now. Let me know if you run into any issues. :)
